### ISSUE TITLE
HTTPClientFactory Not being setup correctly

### ISSUE THREAD

**Issue by robjenman** [Shopify/shopify-php-api#103]
# Issue summary

`Error thrown: Call to a member function client() on null in /var/www/vendor/shopify/shopify-api/src/Clients/Http.php on line 164
`

## Expected behavior

`$client = Context::$HTTP_CLIENT_FACTORY->client();` Should be returning a working Guzzle client however it isnt. Apologies it's late here but `Context::initialize()` is never called as far as I can see and so `$HTTP_CLIENT_FACTORY` is never populated with the Guzzle client that is relied on.

## Steps to reproduce the problem

1. Run composer for version 1.0.0
2. Make a very basic call like  `new \Shopify\Clients\Rest($url, $accessToken)->get('orders');`

**Comment by paulomarg** [comment]
Hi @Chutney, in order to make any requests to the Admin API you'll need to call `Context::initialize`, even if you're using a private app. You can see all of the parameters at https://github.com/Shopify/shopify-php-api/blob/main/docs/getting_started.md, and you'll need to set:
- `apiKey`: your private app's API key
- `apiSecretKey`: your private app's password
- `isPrivateApp`: true

You can see your private app's settings in your Admin:
- Go to `Apps`
- Click on `Manage private apps` under the app list
- Click on your app's name
- Your app's details will be under the Admin API section, as `API key` and `password`

I'll update the documentation to make it easier to see how to use the api key and password for private apps, thank you for raising this!

**Comment by omolto** [comment]
+1

**Comment by faridmovsumov** [comment]
I have the same problem

**Comment by darius00klokj** [comment]
hey guys,

Call the Context::initialize static function,  you will need KEY, SECRET, SCOPES, SHOP NAME and a FileStorageSession. 
The first 3 you get from the dev app created on your shopify dashboard. 

As example

`Context::initialize(
            getenv('SHOP_APP_KEY'),
            getenv('SHOP_APP_SECRET'),
            'read_customers, 
            read_discounts, 
            read_discovery, 
            read_draft_orders, 
            read_assigned_fulfillment_orders, 
            read_merchant_managed_fulfillment_orders, 
            read_order_edits, read_orders, 
            write_orders, 
            read_third_party_fulfillment_orders, 
            read_order_submission_rules',
            getenv('SHOP_APP_NAME'),
            new FileSessionStorage('/tmp/php_sessions')
        );  `

Run the initialize before your Rest api calls.

**Comment by nadar** [comment]
@conradfr 

You can do this ugly workaround

```php
Context::$HTTP_CLIENT_FACTORY = new HttpClientFactory;
$client = new Graphql(...,...);
```

**Comment by conradfr** [comment]
Thanks @nadar it works.

Although sometimes I get an _UninitializedContextException_  
`Context has not been properly initialized. Please call the .initialize() method to set up your app context object.` and retying the request works ...

So people reading this may think of handling that.
