### ISSUE TITLE
Is it possible to allow v2.* for psr/log ?

### ISSUE THREAD

**Issue by ugurarici** [Shopify/shopify-php-api#113]
## Overview/summary
Required version of `psr/log` can be updated so it won't be a conflict with other packages which uses a newer version of `psr/log`

## Motivation

> What inspired this enhancement?

When I tried to install this package on a Laravel 8 project, composer couldn't install it because my project uses `psr/log 2.^`
I downgraded `psr/log` version on my project since most of packages depends on it also accepts version `1.*` 

### Area

- [ ] Add any relevant `Area: <area>` labels to this issue

---

## Checklist

- [x] I have described this enhancement in a way that is actionable (if possible)

**Comment by paulomarg** [comment]
Unfortunately, I don't think we'll be able to bump the log version to 2 just yet - we're currently supporting PHP>=7.3, and as per [the psr/log packagist page](https://packagist.org/packages/psr/log#2.0.0), v2 requires PHP>=8.0, so it would cause conflicts.

Since we won't be able to action this yet, I'll go ahead and close this issue, but please feel free to open more issues if you have any problems.

**Comment by eafarooqi** [comment]
Hi, 

need to use it with laravel 8 and psr 2.0, When it will be possible to use it with php 8? any timeline?
